# Generated by Django 4.1 on 2022-09-29 18:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
