# Generated by Django 4.1 on 2022-09-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_contact_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='content',
        ),
    ]
