# Generated by Django 4.1 on 2022-09-30 11:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_contact_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
